---
version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: blazebooru
      POSTGRES_USER: blazebooru
      POSTGRES_DB: blazebooru
    ports:
      - "5432:5432"
